apiVersion: v1
kind: Service
metadata:
  labels:
    app: influx
  name: influx
spec:
  type: LoadBalancer
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
  selector:
    app: influx