apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: yr-gribdown
spec:
  schedule: "15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: yr-gribdown
            image: nilslarsgard/gribdown:0.5
          restartPolicy: OnFailure